title: Rodrigo Alzola # your name (or website title) here
logo: "/images/yo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a electrical civil engineer form Chile. My interes are automatisation, biotech, software/hardware design and research. 
  My specialty is computer vision, in which I've develope projects in biomedical imaging, but I like to be envolve in different
  and new projects. I love the idea of keep learning and apply engineering in different fields. My life in Chile has shown me 
  the urgent need of think of creative, efficient, and quality ideas for solving the diverse problems. 
  Aside of engineering, I enjoy playing guitarr and flute, training martial arts, playing card games and hiking in excursions. 
  <br><br>
  Second description 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
