title: Rodrigo Alzola # your name (or website title) here
logo: "/images/yo_circular.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an Electrical Civil Engineer form Chile. My interes are automatisation, biotech, software/hardware design and research. 
  My specialty is computer vision, but I like to be envolve in different and new projects. 
  I love to keep learning and apply engineering in different fields, as my life in Chile has shown me the urgent need of 
  think of creative, efficient, and quality ideas for solving diverse problems. Aside of engineering, I enjoy playing guitarr and flute, 
  training martial arts and hiking. 
  
  
  <br><br>
  <a href="https://www.linkedin.com/in/rodrigo-alzola-ab40a9197/">My LinkedIn Profile</a> 
  
  <br>
  Email: ralzola@miuandes.cl <br>
  Phone: (+1)8572254552 ; (+56)979166920

theme: jekyll-theme-minimal
